import React from "react";
import { Composition } from "remotion";
import { AppleAd } from "./AppleAd";

// Generated by build_assets.py — sits at the project root, next to package.json.
// Requires "resolveJsonModule": true in tsconfig.json (Remotion's default
// templates already have this).
import timings from "../timings.json";

export const RemotionRoot: React.FC = () => {
  return (
    <Composition
      id="ProjectTrackAd"
      component={AppleAd}
      // Nothing here is hardcoded — the total length is derived entirely
      // from the voiceover-driven scene lengths computed in Python.
      durationInFrames={timings.totalDurationInFrames}
      fps={timings.fps}
      width={1920}
      height={1080}
      defaultProps={{ timings }}
    />
  );
};
